---
Name: Aqua Security
Website: https://www.aquasec.com
Swag:
  - shirt
  - mask
  - stickers
Description: "We are looking for meaningful contributions to our open source products. It can be adding new features, fixing bugs, improving documentation, integrating with other software, or just creating content in other places that educates about our technology. By getting involved, you get a unique opportunity to apply your skills at the forefront of the cloud native security."
Details: https://blog.aquasec.com/hacktoberfest-2020-aqua-open-source
